### ISSUE TITLE
Straightforward and simple. Nice!

### ISSUE THREAD

**Issue by raymelon** [drixlerangelo/docker-web-app#1]
Dude, this is nice. Looking at it, this repository shows a straightforward, clear, and simple demonstration on configuring multiple domains, self-signed certificates, and addresses through Apache. Things that I think will help beginners get comfortable on configuring their own boxes. I will love contributing a README if you allow. Cheers!

**Comment by drixlerangelo** [comment]
Thank you for the remarks, much appreciated! 😁 Some files are needed to be changed so it can be used as a reference. Thanks for the lending a hand buddy, any help will do. 😄 You can contribute to the README while I'll be on the files itself.
